name: Autograding Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jasmine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
      - run: | 
            npm install 
            npm run test-grading-fetch